
import java.awt.*;
import java.io.File;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ASUS
 */
public class create_post extends javax.swing.JFrame {

    JFileChooser jfc;
    File f;

    /**
     * Creates new form create_post
     */
    public create_post() {
        initComponents();
        jfc = new JFileChooser();

        ImageIcon ic = new ImageIcon("C:\\Users\\ASUS\\Downloads\\user.png");
        Image img = ic.getImage().getScaledInstance(img_lb.getWidth(),
                img_lb.getHeight(), Image.SCALE_SMOOTH);
        ic = new ImageIcon(img);
        img_lb.setIcon(ic);

        setSize(700, 700);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        browse_bt = new javax.swing.JButton();
        img_lb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        caption_ta = new javax.swing.JTextArea();
        submit_bt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("pick an image");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 190, 90, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("CREATE POST");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 60, 170, 32);

        browse_bt.setText("browse");
        browse_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse_btActionPerformed(evt);
            }
        });
        getContentPane().add(browse_bt);
        browse_bt.setBounds(510, 170, 75, 23);

        img_lb.setText("image preview");
        getContentPane().add(img_lb);
        img_lb.setBounds(205, 140, 260, 175);

        jLabel4.setText("enter caption");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 410, 80, 16);

        caption_ta.setColumns(20);
        caption_ta.setRows(5);
        jScrollPane1.setViewportView(caption_ta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 400, 234, 86);

        submit_bt.setText("Submit");
        submit_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btActionPerformed(evt);
            }
        });
        getContentPane().add(submit_bt);
        submit_bt.setBounds(300, 540, 72, 23);

        jButton1.setText("go back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 20, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browse_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse_btActionPerformed
        // TODO add your handling code here:
        int ans = jfc.showOpenDialog(this);

        if (ans == JFileChooser.APPROVE_OPTION) {
            f = jfc.getSelectedFile();
            ImageIcon ic = new ImageIcon(f.getPath());
            Image img = ic.getImage().getScaledInstance(img_lb.getWidth(),
                    img_lb.getHeight(), Image.SCALE_SMOOTH);
            ic = new ImageIcon(img);
            img_lb.setIcon(ic);
        }
    }//GEN-LAST:event_browse_btActionPerformed

    private void submit_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btActionPerformed
        // TODO add your handling code here:
        String name = global.username;
        String caption = caption_ta.getText();

        if (name.isEmpty() || caption.isEmpty()) {
            JOptionPane.showMessageDialog(this, "all fields mandatory");
            return;
        }

        System.out.println("name = " + name + "\ncaption = " + caption);
        String ans = MyClient.create_post(name, caption, f);

        if (ans.equals("pass")) {
            JOptionPane.showMessageDialog(this, "post created successfully");
            //homepage.get_posts();
            homepage obj = new homepage();
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "post failed");
        }

    }//GEN-LAST:event_submit_btActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        homepage obj = new homepage();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create_post().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse_bt;
    private javax.swing.JTextArea caption_ta;
    private javax.swing.JLabel img_lb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submit_bt;
    // End of variables declaration//GEN-END:variables
}
