/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
import java.awt.Image;
import java.io.File;
import javax.swing.*;

public class create_story extends javax.swing.JFrame {

    /**
     * Creates new form create_story
     */
    JFileChooser jfc;
    File f;

    public create_story() {
        initComponents();

        ImageIcon ic = new ImageIcon("C:\\Users\\ASUS\\Downloads\\user.png");
        Image img = ic.getImage().getScaledInstance(image_lb.getWidth(),
                image_lb.getHeight(), Image.SCALE_SMOOTH);
        ic = new ImageIcon(img);
        image_lb.setIcon(ic);

        jfc = new JFileChooser();

        setSize(500, 550);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        image_lb = new javax.swing.JLabel();
        browse_bt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        caption_ta = new javax.swing.JTextArea();
        create_bt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Create Story");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 50, 170, 32);

        jLabel2.setText("upload photo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 80, 16);

        image_lb.setText("image preview");
        getContentPane().add(image_lb);
        image_lb.setBounds(120, 150, 220, 160);

        browse_bt.setText("browse");
        browse_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse_btActionPerformed(evt);
            }
        });
        getContentPane().add(browse_bt);
        browse_bt.setBounds(370, 150, 75, 23);

        jLabel4.setText("caption:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 370, 60, 16);

        caption_ta.setColumns(20);
        caption_ta.setRows(5);
        jScrollPane1.setViewportView(caption_ta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 360, 290, 86);

        create_bt.setText("create!");
        create_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_btActionPerformed(evt);
            }
        });
        getContentPane().add(create_bt);
        create_bt.setBounds(200, 470, 72, 23);

        jButton1.setText("go back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 20, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browse_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse_btActionPerformed
        // TODO add your handling code here:
        int ans = jfc.showOpenDialog(this);

        if (ans == JFileChooser.APPROVE_OPTION) {
            f = jfc.getSelectedFile();
            ImageIcon ic = new ImageIcon(f.getPath());
            Image img = ic.getImage().getScaledInstance(image_lb.getWidth(),
                    image_lb.getHeight(), Image.SCALE_SMOOTH);
            ic = new ImageIcon(img);

            image_lb.setIcon(ic);
        }
    }//GEN-LAST:event_browse_btActionPerformed

    private void create_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_btActionPerformed
        // TODO add your handling code here:
        String caption = caption_ta.getText();

        if (caption.isEmpty() || f == null) {
            JOptionPane.showMessageDialog(this, "all fields mandatory");
            return;
        }

        String ans = MyClient.create_story(global.username, f, caption);

        if (ans.equals("pass")) {
            JOptionPane.showMessageDialog(this, "story created successfully");
            homepage obj = new homepage();
            dispose();
        } else
            JOptionPane.showMessageDialog(this, "story failed");
    }//GEN-LAST:event_create_btActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        homepage obj = new homepage();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_story.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_story.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_story.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_story.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create_story().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse_bt;
    private javax.swing.JTextArea caption_ta;
    private javax.swing.JButton create_bt;
    private javax.swing.JLabel image_lb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
