
import VMM.DBLoader;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.*;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ASUS
 */
public class follower_following_page extends javax.swing.JFrame {

    /**
     * Creates new form follower_following_page
     */
    public follower_following_page(String s) {
        initComponents();

        setSize(380, 700);
        setVisible(true);
        setLocationRelativeTo(null);

        if (s.equals("followers")) {
            get_followers();
        } else if (s.equals("following")) {
            get_following();
        }
    }

    void get_followers() {
        String ans = "";
        //get all followers of global.username
        try {
            ResultSet rs = DBLoader.executeSQL("select * from followers where followed_to = '" + global.username + "'");

            while (rs.next()) {
                String f = rs.getString("followed_by");
                ans += f + "$";
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        //now make objects of accounts and add to panel
        StringTokenizer st = new StringTokenizer(ans, "$");
        int n = st.countTokens();
        int x = 10, y = 10;

        for (int i = 1; i <= n; i++) {
            String user = st.nextToken();
            accounts obj = new accounts();
            String photo = "";

            ResultSet rs = DBLoader.executeSQL("select * from user_table where username = '" + user + "'");
            try {
                rs.next();
                photo = rs.getString("photo");
            } catch (Exception e) {
                e.printStackTrace();
            }

            ImageIcon ic = new ImageIcon(photo);
            Image img = ic.getImage().getScaledInstance(obj.photo_lb.getWidth(),
                    obj.photo_lb.getHeight(), Image.SCALE_SMOOTH);
            ic = new ImageIcon(img);

            obj.photo_lb.setIcon(ic);
            obj.user_lb.setText(user);
            obj.follow_bt.setText("remove");

            obj.setBounds(x, y, 330, 120);

            y += 150;

            jPanel1.add(obj);

            obj.repaint();

            jPanel1.repaint();
            jPanel1.revalidate();
        }

        jPanel1.setPreferredSize(new Dimension(350, y + 20));
    }

    void get_following() {
        String ans = "";
        //get all following of global.username
        try {
            ResultSet rs = DBLoader.executeSQL("select * from followers where followed_by = '" + global.username + "'");

            while (rs.next()) {
                String f = rs.getString("followed_to");
                ans += f + "$";
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        //now make objects of accounts and add to panel
        StringTokenizer st = new StringTokenizer(ans, "$");
        int n = st.countTokens();
        int x = 10, y = 10;

        for (int i = 1; i <= n; i++) {
            String user = st.nextToken();
            accounts obj = new accounts();
            String photo = "";

            ResultSet rs = DBLoader.executeSQL("select * from user_table where username = '" + user + "'");
            try {
                rs.next();
                photo = rs.getString("photo");
            } catch (Exception e) {
                e.printStackTrace();
            }

            ImageIcon ic = new ImageIcon(photo);
            Image img = ic.getImage().getScaledInstance(obj.photo_lb.getWidth(),
                    obj.photo_lb.getHeight(), Image.SCALE_SMOOTH);
            ic = new ImageIcon(img);

            obj.photo_lb.setIcon(ic);
            obj.user_lb.setText(user);
            obj.follow_bt.setText("unfollow");

            obj.setBounds(x, y, 330, 120);

            y += 150;

            jPanel1.add(obj);

            obj.repaint();

            jPanel1.repaint();
            jPanel1.revalidate();
        }

        jPanel1.setPreferredSize(new Dimension(350, y + 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 340, 590);

        jButton1.setText("get back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 20, 75, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        user_profile obj = new user_profile();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
