
import VMM.DBLoader;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ASUS
 */
public class forgot_password extends javax.swing.JFrame {

    /**
     * Creates new form forgot_password
     */
    ResultSet rs;
    String otp;

    public forgot_password() {
        initComponents();

        verify_bt.setEnabled(false);

        setVisible(true);
        setSize(500, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email_tf = new javax.swing.JTextField();
        submit_bt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        otp_tf = new javax.swing.JTextField();
        verify_bt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        user_tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Forgot Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 50, 190, 40);

        jLabel2.setText("email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 190, 80, 16);
        getContentPane().add(email_tf);
        email_tf.setBounds(210, 190, 170, 30);

        submit_bt.setText("submit");
        submit_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btActionPerformed(evt);
            }
        });
        getContentPane().add(submit_bt);
        submit_bt.setBounds(250, 240, 90, 23);

        jLabel3.setText("enter otp");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 330, 80, 16);
        getContentPane().add(otp_tf);
        otp_tf.setBounds(210, 320, 170, 30);

        verify_bt.setText("verify");
        verify_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify_btActionPerformed(evt);
            }
        });
        getContentPane().add(verify_bt);
        verify_bt.setBounds(250, 380, 90, 23);

        jLabel4.setText("username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 140, 70, 16);
        getContentPane().add(user_tf);
        user_tf.setBounds(210, 140, 170, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verify_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify_btActionPerformed
        // TODO add your handling code here:

        System.out.println("In Verify button");
        String otp = otp_tf.getText();
        String username = user_tf.getText();
        String password = "";

        try {
            ResultSet rs1 = DBLoader.executeSQL("select * from user_table where username = '" + username + "' ");
            rs1.next();

            password = rs1.getString("password");
            System.out.println("Password " + password);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        if (otp.equals(this.otp)) {
            JOptionPane.showMessageDialog(this, "otp matches!");

            JOptionPane.showMessageDialog(this, "this is your password = '" + password + "'");
            login obj = new login();
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "otp does not match");
        }
    }//GEN-LAST:event_verify_btActionPerformed

    private void submit_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btActionPerformed
        // TODO add your handling code here:

        String email = email_tf.getText();

        try {
            rs = DBLoader.executeSQL("select * from user_table where email='" + email + "'");
            if (rs.next()) {
                otp = (int) (1000 + (9999 - 1000) * Math.random()) + "";
                sendemail obj = new sendemail(email, "Password recovery",
                        "The one time password for forgot password is " + otp);
                obj.sendemail();
                verify_bt.setEnabled(true);

                JOptionPane.showMessageDialog(this, "OTP Sent");
            } else {
                JOptionPane.showMessageDialog(this, "Email not registered");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_submit_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField otp_tf;
    private javax.swing.JButton submit_bt;
    private javax.swing.JTextField user_tf;
    private javax.swing.JButton verify_bt;
    // End of variables declaration//GEN-END:variables
}
