
import VMM.DBLoader;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author ASUS
 */
public class post extends javax.swing.JPanel {

    /**
     * Creates new form post
     */
    public post() {
        initComponents();
        ImageIcon ic = new ImageIcon("C:\\Users\\ASUS\\Downloads\\user.png");
        Image img = ic.getImage().getScaledInstance(img_lb.getWidth(),
                img_lb.getHeight(), Image.SCALE_SMOOTH);
        ic = new ImageIcon(img);
        img_lb.setIcon(ic);

        post_id_lb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_lb = new javax.swing.JLabel();
        img_lb = new javax.swing.JLabel();
        caption_lb = new javax.swing.JLabel();
        like_bt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        post_id_lb = new javax.swing.JLabel();
        like_count_lb = new javax.swing.JLabel();

        setLayout(null);

        user_lb.setText("username");
        add(user_lb);
        user_lb.setBounds(40, 50, 180, 16);

        img_lb.setText("image");
        add(img_lb);
        img_lb.setBounds(40, 110, 400, 250);

        caption_lb.setText("caption");
        add(caption_lb);
        caption_lb.setBounds(40, 370, 370, 90);

        like_bt.setText("Like");
        like_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                like_btActionPerformed(evt);
            }
        });
        add(like_bt);
        like_bt.setBounds(350, 50, 72, 23);

        jLabel1.setText("total likes = ");
        add(jLabel1);
        jLabel1.setBounds(330, 80, 70, 16);

        post_id_lb.setText("post_id");
        add(post_id_lb);
        post_id_lb.setBounds(40, 460, 70, 16);

        like_count_lb.setText("0");
        add(like_count_lb);
        like_count_lb.setBounds(410, 80, 37, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void like_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_like_btActionPerformed
        // TODO add your handling code here:

        int post_id = Integer.parseInt(post_id_lb.getText());
        System.out.println("global = " + global.username + "\npost_id = " + post_id);

        if (like_bt.getText().equals("like")) {
            //create row in like_post
            ResultSet rs = DBLoader.executeSQL("select*from like_post");
            try {
                while (rs.next()) {
                }

                rs.moveToInsertRow();

                rs.updateString("username", global.username);
                rs.updateInt("post_id", post_id);

                rs.insertRow();

                int likes = Integer.parseInt(like_count_lb.getText()) + 1;
                like_count_lb.setText(likes + "");
                like_bt.setText("unlike");
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
            //unlike => delete row from like_post
            ResultSet rs = DBLoader.executeSQL("select*from like_post where post_id = " + post_id
                    + " and username = '" + global.username + "'");
            try {
                rs.next();
                rs.deleteRow();

                int likes = Integer.parseInt(like_count_lb.getText()) - 1;
                like_count_lb.setText(likes + "");
                like_bt.setText("like");
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

//        homepage.get_posts();
    }//GEN-LAST:event_like_btActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel caption_lb;
    public javax.swing.JLabel img_lb;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton like_bt;
    public javax.swing.JLabel like_count_lb;
    public javax.swing.JLabel post_id_lb;
    public javax.swing.JLabel user_lb;
    // End of variables declaration//GEN-END:variables
}
