/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class Server_On_Off extends javax.swing.JFrame {

    MyServer obj;

    /**
     * Creates new form Server_On_Off
     */
    public Server_On_Off() {
        initComponents();

        off_bt.setEnabled(false);

        setSize(600, 600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        off_bt = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        on_bt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setText("SERVER  ON/OFF");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 80, 220, 32);

        off_bt.setText("Server OFF");
        off_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                off_btActionPerformed(evt);
            }
        });
        getContentPane().add(off_bt);
        off_bt.setBounds(230, 250, 110, 23);

        jButton3.setText("Get Started");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 310, 110, 23);

        on_bt.setText("Server  ON");
        on_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_btActionPerformed(evt);
            }
        });
        getContentPane().add(on_bt);
        on_bt.setBounds(230, 190, 110, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void on_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_btActionPerformed
        // TODO add your handling code here:
        try {
            obj = new MyServer(9000);

            //changes in enable of buttons
            on_bt.setEnabled(false);
            off_bt.setEnabled(true);

        } catch (Exception ex) {
//            System.out.println("failed to start server");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_on_btActionPerformed

    private void off_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_off_btActionPerformed
        // TODO add your handling code here:
        obj.shutdown();

        on_bt.setEnabled(true);
        off_bt.setEnabled(false);
    }//GEN-LAST:event_off_btActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        getStarted obj = new getStarted();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server_On_Off.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server_On_Off.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server_On_Off.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server_On_Off.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server_On_Off().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton off_bt;
    private javax.swing.JButton on_bt;
    // End of variables declaration//GEN-END:variables
}
