
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author ASUS
 */
public class user_post extends javax.swing.JPanel {

    /**
     * Creates new form user_post
     */
    public user_post() {
        initComponents();
        post_id_lb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image_lb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        like_count_lb = new javax.swing.JLabel();
        post_id_lb = new javax.swing.JLabel();

        setLayout(null);

        image_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_lb.setText("image");
        image_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                image_lbMouseClicked(evt);
            }
        });
        add(image_lb);
        image_lb.setBounds(6, 6, 200, 170);

        jLabel2.setText("likes = ");
        add(jLabel2);
        jLabel2.setBounds(57, 190, 50, 16);

        like_count_lb.setText("0");
        add(like_count_lb);
        like_count_lb.setBounds(120, 190, 37, 16);

        post_id_lb.setText("post_id");
        add(post_id_lb);
        post_id_lb.setBounds(320, 80, 60, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void image_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image_lbMouseClicked
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(this, "confirm deletetion of post",
                "delete post", JOptionPane.YES_NO_OPTION);

        if (ans == JOptionPane.YES_OPTION) {
            int post_id = Integer.parseInt(post_id_lb.getText());
            String a = MyClient.delete_post(post_id);
            if (a.equals("pass")) {
                JOptionPane.showMessageDialog(this, "deleted successfully");
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "deletion failed");
            }
        } else {
            JOptionPane.showMessageDialog(this, "delete cancelled");
        }
    }//GEN-LAST:event_image_lbMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel image_lb;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel like_count_lb;
    public javax.swing.JLabel post_id_lb;
    // End of variables declaration//GEN-END:variables
}
