
import VMM.DBLoader;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.*;
import java.util.StringTokenizer;
//import java.util.StringTokenizer;
import javax.swing.ImageIcon;

public class user_profile extends javax.swing.JFrame {

    public user_profile() {
        initComponents();

        setVisible(true);
        setSize(800, 800);
        setLocationRelativeTo(null);

        start_user_profile();
    }

    public void start_user_profile() {
        //do counting
        try {
            //count followers
            ResultSet rs = DBLoader.executeSQL("select count(*) as count from followers where followed_to = '"
                    + global.username + "'");
            rs.next();
            int count = rs.getInt("count");

            follower_lb.setText(count + "");

            //count following
            rs = DBLoader.executeSQL("select count(*) as count from followers where followed_by = '"
                    + global.username + "'");
            rs.next();
            count = rs.getInt("count");

            following_lb.setText(count + "");

            //image
            rs = DBLoader.executeSQL("select photo from user_table where username = '" + global.username + "'");
            rs.next();

            String photo = rs.getString("photo");

            ImageIcon ic = new ImageIcon(photo);
            Image img = ic.getImage().getScaledInstance(image_lb.getWidth(),
                    image_lb.getHeight(), Image.SCALE_SMOOTH);
            ic = new ImageIcon(img);

            image_lb.setIcon(ic);

            //username
            username_lb.setText(global.username);

            //now posts
            String posts = MyClient.get_self_posts();
            System.out.println("self posts = " + posts);

            StringTokenizer st1 = new StringTokenizer(posts, "^");
            int n = st1.countTokens();

            int x = 40, y = 20, countPost = 0;

            for (int i = 1; i <= n; i++) {
                StringTokenizer st2 = new StringTokenizer(st1.nextToken(), "$");

                int pi = Integer.parseInt(st2.nextToken());
                String ph = st2.nextToken();
//                String cp = st2.nextToken();

                user_post objPost = new user_post();

                //data fill
//                objPost.post_id_lb.setText(pi + "");
//                objPost.caption_lb.setText(cp);
//                objPost.user_lb.setText(global.username);
                ic = new ImageIcon(ph);
                img = ic.getImage().getScaledInstance(objPost.image_lb.getWidth(),
                        objPost.image_lb.getHeight(), Image.SCALE_SMOOTH);
                ic = new ImageIcon(img);

                objPost.image_lb.setIcon(ic);

                objPost.post_id_lb.setText(pi + "");

                //like count
                rs = DBLoader.executeSQL("select count(*) as count from like_post where post_id = " + pi);
                rs.next();
                count = rs.getInt("count");
                objPost.like_count_lb.setText(count + "");

                objPost.setBounds(x, y, 210, 210);

                //40 + 210 + 20 + 210 + 20 + 210 + 20 = 710
                if (x < 500) {
                    x += 230;  //210 + 20
                } else {
                    x = 40;
                    y += 230;
                }
                countPost++;
                jPanel1.add(objPost);

//                y += 550;
                objPost.repaint();
//                objPost.revalidate();
                jPanel1.repaint();
                jPanel1.revalidate();
            }
            System.out.println("total posts = " + countPost);
            jPanel1.setPreferredSize(new Dimension(770, y + 250));

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image_lb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        username_lb = new javax.swing.JLabel();
        follower_lb = new javax.swing.JLabel();
        followers_bt = new javax.swing.JButton();
        following_lb = new javax.swing.JLabel();
        following_bt = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        image_lb.setText("image");
        getContentPane().add(image_lb);
        image_lb.setBounds(10, 50, 230, 170);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 780, 600);

        username_lb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        username_lb.setText("username");
        getContentPane().add(username_lb);
        username_lb.setBounds(260, 80, 130, 30);

        follower_lb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        follower_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        follower_lb.setText("0");
        getContentPane().add(follower_lb);
        follower_lb.setBounds(280, 150, 37, 25);

        followers_bt.setText("followers");
        followers_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followers_btActionPerformed(evt);
            }
        });
        getContentPane().add(followers_bt);
        followers_bt.setBounds(260, 180, 80, 23);

        following_lb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        following_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        following_lb.setText("0");
        getContentPane().add(following_lb);
        following_lb.setBounds(470, 150, 30, 25);

        following_bt.setText("following");
        following_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                following_btActionPerformed(evt);
            }
        });
        getContentPane().add(following_bt);
        following_bt.setBounds(440, 180, 80, 23);

        jButton3.setText("edit profile");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(630, 70, 120, 30);

        jButton1.setText("get back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 10, 75, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void followers_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followers_btActionPerformed
        // TODO add your handling code here:
        follower_following_page obj = new follower_following_page("followers");
        dispose();
    }//GEN-LAST:event_followers_btActionPerformed

    private void following_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_following_btActionPerformed
        // TODO add your handling code here:
        follower_following_page obj = new follower_following_page("following");
        dispose();
    }//GEN-LAST:event_following_btActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        edit_profile obj = new edit_profile();

//        String ans = MyClient.get_user_info();
//
//        StringTokenizer st = new StringTokenizer(ans, "$");
//        String email = st.nextToken();
//        String photo = st.nextToken();
//        String mobile = st.nextToken();
//        String gender = st.nextToken();
        try {
            ResultSet rs = DBLoader.executeSQL("select * from user_table where username = '" + global.username + "'");
            rs.next();

            String email = rs.getString("email");
            String mobile = rs.getString("mobile");
            String gender = rs.getString("gender");
            String photo = rs.getString("photo");

            obj.username_lb.setText(global.username);
            obj.email_tf.setText(email);
            obj.mobile_tf.setText(mobile);

            if (gender.equals("Male")) {
                obj.male_rbt.setSelected(true);
            } else {
                obj.female_rbt.setSelected(true);
            }

            ImageIcon ic = new ImageIcon(photo);
            Image img = ic.getImage().getScaledInstance(obj.image_lb.getWidth(),
                    obj.image_lb.getHeight(), Image.SCALE_SMOOTH);
            ic = new ImageIcon(img);
            obj.image_lb.setIcon(ic);

            dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        homepage obj = new homepage();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel follower_lb;
    private javax.swing.JButton followers_bt;
    private javax.swing.JButton following_bt;
    public javax.swing.JLabel following_lb;
    public javax.swing.JLabel image_lb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel username_lb;
    // End of variables declaration//GEN-END:variables
}
